### ISSUE TITLE
App crash after upgrading Gradle to 3.5.0

### ISSUE THREAD

**Issue by palicka** [twilio/twilio-chat-demo-android#100]
stack trace:
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/******/base.apk:classes3.dex)
        at com.twilio.video.EglBaseProvider.<init>(EglBaseProvider.java:93)
        at com.twilio.video.EglBaseProvider.instance(EglBaseProvider.java:37)
        at com.twilio.video.VideoTextureView.onAttachedToWindow(VideoTextureView.java:107)
        at android.view.View.dispatchAttachedToWindow(View.java:18623)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3527)

I found similar bug [here](https://github.com/jitsi/jitsi-meet/issues/4562) maybe it will help...

**Comment by rusmonster** [comment]
@palicka this is chat sdk repo and the stacktrace shows crash related to the video sdk. Please contact support@twilio.com with this issue
